import React from "react";
import { Compass, Github, Twitter, Heart } from "lucide-react";

export default function Footer() {
  return (
    <footer className="bg-slate-900 text-slate-400 py-12 border-t border-slate-800 dark:bg-slate-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Brand */}
          <div className="col-span-1 md:col-span-2">
            <div className="flex items-center gap-2 text-white text-xl font-bold mb-4">
              <Compass className="h-6 w-6 text-primary-500 animate-pulse-slow" />
              <span>TripPlanner AI</span>
            </div>
            <p className="text-sm text-slate-400 max-w-sm">
              Discover your next destination with personalized day-by-day itineraries generated by advanced AI and retrieved travel documentation.
            </p>
          </div>

          {/* Links */}
          <div>
            <h3 className="text-white font-semibold mb-4 text-sm uppercase tracking-wider">Product</h3>
            <ul className="space-y-2 text-sm">
              <li><a href="/planner" className="hover:text-primary-400 transition-colors">AI Trip Planner</a></li>
              <li><a href="/chat" className="hover:text-primary-400 transition-colors">Chat Assistant</a></li>
              <li><a href="/saved" className="hover:text-primary-400 transition-colors">My Saved Trips</a></li>
            </ul>
          </div>

          {/* Social */}
          <div>
            <h3 className="text-white font-semibold mb-4 text-sm uppercase tracking-wider">Follow Us</h3>
            <div className="flex space-x-4 mb-4">
              <a href="#" className="p-2 bg-slate-800 rounded-lg hover:bg-primary-600 hover:text-white transition-all">
                <Twitter className="h-4 w-4" />
              </a>
              <a href="#" className="p-2 bg-slate-800 rounded-lg hover:bg-primary-600 hover:text-white transition-all">
                <Github className="h-4 w-4" />
              </a>
            </div>
            <p className="text-xs text-slate-500">
              © {new Date().getFullYear()} TripPlanner AI. All rights reserved.
            </p>
          </div>
        </div>

        <div className="border-t border-slate-800 mt-8 pt-8 flex items-center justify-between text-xs text-slate-500">
          <p>Designed for premium travelers everywhere.</p>
          <p className="flex items-center gap-1">
            Made with <Heart className="h-3 w-3 text-red-500 fill-red-500" /> for AI exploration.
          </p>
        </div>
      </div>
    </footer>
  );
}
